#!/usr/bin/python3
import os
import subprocess
import zipfile

zipname = 'build/from-python-import-better.zip'

subprocess.check_call(['tox', '-e', 'tex', '-e', 'book', '-e', 'html'])
if os.path.exists(zipname):
    os.remove(zipname)
with zipfile.ZipFile(zipname, 'w') as zipf:
    zipf.write('build/tox/html/tmp/html/frompythonimportbetter.epub', 'from-python-import-better.epub')
    zipf.write('build/tox/tex/tmp/tex/frompythonimportbetter.pdf',
               'from-python-import-better.pdf')
    html = 'build/tox/book/tmp/html'
    for root, dirs, files in os.walk(html):
        for file in files:
            fname = os.path.join(root, file)
            relname = os.path.join('html', os.path.relpath(fname, html))
            zipf.write(fname, relname)
